Paginate = 10
baseURL = "https://dazzling-bose-834fdc.netlify.com/"
copyright = ""
defaultContentLanguage = "en"
disqusShortname = ""
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
preserveTaxonomyNames = true
pygmentsCodefences = true
theme = "minimo"
title = "blog"
[blackfriday]
hrefTargetBlank = true
[languages.en]
lang = "en"
languageName = "English"
weight = 1
[[menu.main]]
identifier = "repository"
name = "Repo"
url = "https://github.com/MunifTanjim/minimo"
weight = -10
[params.assets]
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
favicon = "favicon.ico"
gopher = ""
[params.comments]
enable = false
[params.comments.staticman]
apiEndpoint = "https://api.staticman.net/v2/entry"
enable = true
maxDepth = 2
[params.comments.staticman.github]
branch = ""
repository = ""
username = ""
[params.comments.utterances]
enable = false
issueTerm = "pathname"
[params.comments.utterances.github]
repository = ""
username = ""
[params.copyright]
holder = "Jason Hoelscher-Obermaier"
prefix = ""
startYear = "2018"
suffix = ""
[params.info]
description = "blog..."
title404 = "Nothing's here!"
[params.opengraph.facebook]
admins = []
appID = ""
pageID = ""
[params.opengraph.twitter]
page = ""
[params.search]
client = ""
[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""
[params.seo]
titleSeparator = "•"
[params.settings]
accentColor = "#ffcd00"
archiveDateFormat = "Jan 02"
dateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"]
hideMainMenu = false
listDateFormat = "2006, Jan 02"
showReadingTime = false
taxonomyCloudShuffle = true
[params.sidebar]
enable = true
[params.social]
codepen = ""
email = "jason.hoelscherobermaier@gmail.com"
facebook = ""
github = "jas-ho"
gitlab = ""
google_scholar = ""
instagram = ""
linkedin = ""
telegram = ""
twitter = ""
youtube = ""
[params.widgets]
footer = ["social_menu"]
homepage = ["recent_posts"]
sidebar = ["about", "search", "sidebar_menu", "taxonomy_cloud"]
[permalinks]
page = "/:slug/"
[taxonomies]
tag = "tags"
